name: Generate Snake Animation

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"
  
  # Allows manual workflow runs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      # Generates the snake  
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Gourabbabu
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Push to the output branch  
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
