name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Gourabbabu
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Push the changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated snake animation"
          add: "output/github-contribution-grid-snake.svg"
